# Site settings
title: Alexander Shabalin's blog
description: >
  Ramblings about software development.
baseurl: ""
url: "https://blog.ashabalin.me"
twitter_username: projedi
github_username:  projedi

# Build settings
markdown: kramdown
